plugins {
    id 'org.jetbrains.kotlin.js' version '1.8.22'
}

group = 'com.nospoon'
version = '1.0-SNAPSHOT'

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
}

kotlin {
    js(IR) {
        browser {
            binaries.executable()

            tasks.getByName(compilations.main.compileKotlinTaskName).kotlinOptions {
                //sourceMap = true //create source maps for js files
                //sourceMapEmbedSources = "always" //embed the kotlin files into the sourcemaps for viewing in the browser
                moduleKind = 'commonjs' //module type to be loaded by webpack
            }
            //testTask {
            //    enabled = false
            //}
            //dceTask {
            //    dceOptions.devMode = true
            //}
        }
        dependencies {
            //implementation 'org.jetbrains.kotlin:kotlin-stdlib-js'
            //implementation "org.jetbrains.kotlinx:kotlinx-serialization-core:$serialization_version"
            //implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime-js:$serialization_version"
            implementation "io.github.hiperbou.imgui-kt:imgui-kt-definitions:0.1.0"
            implementation "io.github.hiperbou.imgui-kt:imgui-kt:0.1.0"

            //implementation npm('karma', '4.3.1')
        }
    }
}